### ISSUE TITLE
Segmentation fault on multiple seeks

### ISSUE THREAD

**Issue by feelfreelinux** [nitroshare/qhttpengine#15] opened 2017-02-23 19:39 UTC
When I try to seek quickly, multiple times using QHttpFilesystemHandler, app crashes with "Segmentation fault".

**Comment by nathan-osman** [comment] 2017-02-23 21:42
When you refer to "seek quickly", do you mean that the client is sending lots of requests with `Content-Range` set and QHttpEngine is crashing? Is there any chance you could run this in a debugger and pinpoint where the crash is occurring? If you are able to provide a simple reproducible example, that would be extremely helpful.

**Comment by feelfreelinux** [comment] 2017-02-23 21:51
@nathan-osman Used fileserver example from examples directory, played video in format MPEG-4 .mp4. Code seems to crash somewhere in QTcpServer, can't get any debuger output directly in signals/etc. Fail is pretty random, even happened on first play. Yes, I reffer to Content-Range requestd

**Comment by nathan-osman** [comment] 2017-02-23 22:32
Okay, I'll see if I can reproduce the crash then.

**Comment by nathan-osman** [comment] 2017-02-23 22:40
Sorry, two more questions :smile:

- Which operating system are you seeing this on?
- Which version of QHttpEngine are you using? (0.1.0 or `master` from Git?)

**Comment by feelfreelinux** [comment] 2017-02-24 06:09
@nathan-osman Using master branch, 0.1.0 does not support seeking. Using ubuntu 14.04.

**Comment by feelfreelinux** [comment] 2017-02-24 11:01
@InfernoCoder - can also approve this.

**Comment by InfernoCoder** [comment] 2017-02-24 12:03
Yep, this bug occurs on my system too. Another segmentation error occurs when I run a video which has higher resolution than supported on my PC. For example, if I run a 4K video on my 1080p PC, the server crashes. Tried on Google Chrome and VLC Player. I'm also running Debian.

**Comment by feelfreelinux** [comment] 2017-02-24 14:25
@nathan-osman Happens really often when trying to launch video in google chrome.

**Comment by InfernoCoder** [comment] 2017-02-24 15:56
@nathan-osman @feelfreelinux I have been able to find a workaround by commenting out the `socket->close();` line in `qfilesystemhandler.cpp`

**Comment by nathan-osman** [comment] 2017-03-26 04:40
I'll take another look at that section.

**Comment by nathan-osman** [comment] 2017-08-08 18:49
I have finally determined the source of the problem and it's quite subtle:

In `ServerPrivate::process()`, the new socket's `disconnected()` signal is connected to `deleteLater()`. At some point after requesting the file, Chrome sends a TCP RST packet, closing the connection. This of course triggers the socket's destructor. Meanwhile, in `FilesystemHandlerPrivate::processFile()`, the `QIODeviceCopier` completes and `finished()` is emitted. Connected to this is a lambda that runs `socket->close()` which triggers a segmentation fault (SIGSEGV).

The correct solution, I believe, is to remove the connection between `Socket::disconnected()` and `Socket::deleteLater()` since this should be handled by the handlers rather than the server itself. I'll be working on a fix for this shortly.

**Closed** 2017-08-08 19:02 UTC
Labels: bug

**Comment by nathan-osman** [comment] 2017-08-08 19:19
I believe this is now fixed. Please let me know if the issue has been resolved.
